### ISSUE TITLE
raise key error

### ISSUE THREAD

**Issue by Chikharom** [PIA-Group/BioSPPy#58]
Hello and thanks for any future help!
I am trying to use Biosppy in combination with pyhrv to analyse an ECG signal and when I try to geenerate the tuples containing all HRV parameters I get this error message :+1: KeyError: 
  File "/home/omar/.local/lib/python2.7/site-packages/biosppy/utils.py", line 407, in __getitem__
    raise KeyError("Unknown key: %r." % key)

KeyError: "Unknown key: 'ar_order'."

**Comment by PGomes92** [comment]
Hi Longshan, 

I'll take the blame on this, as this is a pyHRV specific issue and not a BioSPPy one ;) 

Unfortunately, this issue is known and you can find an [open issue in the pyHRV repository](https://github.com/PGomes92/pyhrv/issues/7) which will be fixed with the next pyHRV update coming over the next couple of days. 

If possible, please post issues that are related to the use of pyHRV directly in the pyHRV repository, this would help me greatly on following-up on known issues and on fixing them.

@hugoslv I believe the BioSPPy team can label this as 'wontfix' and I'll post updates on this issue here once they're available.

**Comment by hugoslv** [comment]
Thanks for the update @PGomes92... a new "out of scope" label has been created. If you could post an update on the issue it would be great.
