### ISSUE TITLE
BVP codes reference

### ISSUE THREAD

**Issue by pritamqu** [PIA-Group/BioSPPy#69]
hi, 
is this module for PPG
https://github.com/PIA-Group/BioSPPy/blob/master/biosppy/signals/bvp.py
?

If yes, the reference/algorithm used in <find_onsets> module is not for PPG, those are for ABP.
just wanted to clarify this doubt.. as BVP and PPG are same but PPG and ABP are not same.

**Comment by MarianaAbreu** [comment]
Hi, 

You are correct. The code of "find_onsets" was based on an article of Arterial Blood Pressure Onsets. However, since BVP and ABP have similar morphologies, the code to detect onsets for one signal can work for the other relatively well. 
Nevertheless, if you find a better alternative we are pleased to integrate it in this module as well.  

Thank you

**Comment by pritamqu** [comment]
I found this one can be useful:
Elgendi M, Norton I, Brearley M, Abbott D, Schuurmans D (2013) Systolic Peak Detection in Acceleration Photoplethysmograms Measured from Emergency Responders in Tropical Conditions.  PLoS ONE 8(10): e76585. doi:10.1371/journal.pone.0076585.

already implemented in neurokit2: https://github.com/neuropsychology/NeuroKit/blob/b12315465db559ef0228470a4c31b85371775896/neurokit2/ppg/ppg_findpeaks.py

not sure if you would like to integrate this one in your library.

**Comment by MarianaAbreu** [comment]
Thank you for the suggestion, this issue was solved by @LeafarCoder  (#70 ) and merged into the master code.

**Comment by pritamqu** [comment]
thanks for making this change.
