### ISSUE TITLE
can i do real time plotting with values fetched from .json file? 

### ISSUE THREAD

**Issue by dheerajluffy** [PIA-Group/BioSPPy#93]

**Comment by afonsocraposo** [comment]
Can you describe in more detail what you are trying to do?
If you provide an example of the values fetched we'll be better able to help you.

**Comment by dheerajluffy** [comment]
sorry for being less informative, i want to plot real time ecg data fetched from ecg sensors, so is there anyway update the values on the graph per certain time?

**Comment by afonsocraposo** [comment]
Hello, thank you for describing your problem.
Maybe you could fetch the data from the ECG sensors periodically to a buffer and apply the ECG analysis functions we provide. If your buffer contains a few seconds of the signal, I don't see why it wouldn't work.
In order to show a plot and update it in real time, you could try something similar to this:
[https://learn.sparkfun.com/tutorials/graph-sensor-data-with-python-and-matplotlib/update-a-graph-in-real-time](https://learn.sparkfun.com/tutorials/graph-sensor-data-with-python-and-matplotlib/update-a-graph-in-real-time)

**Comment by dheerajluffy** [comment]
thanks for sharing the information , i tired to do the same , store the values in a text file and plot but to plot the graph it was asking for more than 100 readings , which caused the delay to plot the graph , the link which you have sent seems will work , i will give that a try , thank you very much for your help really appreciate it :)

**Comment by afonsocraposo** [comment]
Let us know if it worked or not. Feel free to reopen the issue if needed!
